cd C:\Windows\System32
@echo off
cls

AMIDEWINx64.EXE /IVN E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /IV E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /IV E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /SM E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /SP E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /SV E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /SS E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /SU AUTO
AMIDEWINx64.EXE /SK E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /SF E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /BM E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /BP E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /BV E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /BS E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /BT E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /BLC E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /CM E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /CV E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /CS E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /CA E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /CSK E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /PSN E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /PAT E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /PPN E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 1 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 2 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 3 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 4 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 5 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 6 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 7 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 8 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 9 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 10 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%
AMIDEWINx64.EXE /OS 11 E-%RANDOM%-%RANDOM%-%RANDOM%-%RANDOM%

cls
net stop winmgmt /Y >nul
